# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Staging

on:
  push:
    branches: ["main"]

env:
  APP_ENV: ${{ secrets.STAGING }}
  STATUS: "❌"

jobs:
  clear-docker-cache:
    name: "Clear Docker Cache"
    runs-on: [self-hosted, staging]
    steps:
      - name: Docker Prune
        run: sudo docker system prune -f -a --volumes
  build:
    needs: ["clear-docker-cache"]
    name: "Deploy to Staging"
    environment:
      name: staging

    runs-on: [self-hosted, staging]

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create ENV
        run: |
          rm -r -f .env
          touch .env_temp
          echo $APP_ENV | tee .env_temp
          sed 's/ /\n/g' .env_temp >> .env
          rm -r -f .env_temp
      # Reference from offical Docker youtube channel: https://youtu.be/aNh8iShFXto
      - name: Build Docker and deployment
        run: sudo chmod +x docker-build.sh && sudo ./docker-build.sh

      - name: Set build status emoji to success
        run: echo "STATUS=✅" >> $GITHUB_ENV

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: "C05246T9K7G"
          # For posting a simple plain text message
          slack-message:
            "GitHub build result: ${{ job.status }}\nPlease check result
            in\nhttps://github.com/abc-software-solutions-company/lucky-draw-website/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        if: always() # Pick up events even if the job fails or is canceled.
